### ISSUE TITLE
Why do we need to prefix 'JWT ' to token?

### ISSUE THREAD

**Issue by techyvicky** [bradtraversy/nodeauthapp#1]
Hello,

I was following your tutorial from youtube it works fine,
You explained it very well, thank you for that.
I just have a little query why do we need to prefix 'JWT ' to token while sending a response back.
By the way with prefixing 'JWT ' it works fine but as soon as I remove 'JWT ', it didn't work, I'm wondering why this is happening? any specific logical or syntactical reason?

**Comment by vijoytechy** [comment]
Hello  brad,
  I was following your tutorial from youtube, and while running  authentication in postman Iam getting error that `Error: Expected "payload" to be a plain object.
    at validate (/home/vijo/Music/MeanLearn/node_modules/jsonwebtoken/sign.js:34:11)
    at validatePayload (/home/vijo/Music/MeanLearn/node_modules/jsonwebtoken/sign.js:56:10)
    at Object.module.exports [as sign] (/home/vijo/Music/MeanLearn/node_modules/jsonwebtoken/sign.js:108:7)
    at User.comparePassword (/home/vijo/Music/MeanLearn/routes/users.js:41:33)
    at bcrypt.compare (/home/vijo/Music/MeanLearn/models/user.js:46:9)
    at /home/vijo/Music/MeanLearn/node_modules/bcryptjs/dist/bcrypt.js:297:21
    at /home/vijo/Music/MeanLearn/node_modules/bcryptjs/dist/bcrypt.js:1353:21
    at Immediate.next [as _onImmediate] (/home/vijo/Music/MeanLearn/node_modules/bcryptjs/dist/bcrypt.js:1233:21)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
`
Please help me to resolve this 
**passport.js**
`const JwtStrategy = require('passport-jwt').Strategy;
const ExtractJwt = require('passport-jwt').ExtractJwt;
const User = require('../models/user');
const config = require('../config/database');

module.exports = function(passport){
  let opts = {};
  opts.jwtFromRequest = ExtractJwt.fromAuthHeaderWithScheme("jwt");
  opts.secretOrKey = config.secret;
  passport.use(new JwtStrategy(opts, (jwt_payload, done) => {
    User.getUserById(jwt_payload.data._id, (err, user) => {
      if(err){
        return done(err, false);
      }

      if(user){
        return done(null, user);
      } else {
        return done(null, false);
      }
    });
  }));
}`

**Comment by ashishrawat13** [comment]
can you tell me in which line this is written

**Comment by lyamiver** [comment]
Maybe 
JWT defines a special structure of information that is sent over the network. It comes in two forms, serialized and deserialized. The former is used directly to transmit data with requests and responses. On the other hand, to read and write information to a token, it needs to be deserialized.

Also because JWT is one of the most common methods of authentication for requests to Java WEB applications and this type of protection and authentication has several advantages:

convenience (no need to pass login and password with every request);

less queries to the database (the token may contain basic information about the user);

easy implementation (it's enough to use a ready-made library to generate and decrypt a token)
